# Jekyll configuration for BIQL documentation

title: "BIDS Query Language (BQL)"
description: "A powerful SQL-like query language for BIDS neuroimaging datasets"
url: "https://username.github.io"
baseurl: "/biql"

# Theme configuration
remote_theme: just-the-docs/just-the-docs
color_scheme: nil

# Repository information
repository: "username/biql"
edit_page: true
edit_repository: "https://github.com/username/biql"
edit_branch: "main"

# Search configuration
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s\-/]+/
  button: false

# Navigation
nav_sort: case_sensitive
nav_external_links:
  - title: "GitHub Repository"
    url: "https://github.com/username/biql"
    hide_icon: false

# Features
back_to_top: true
back_to_top_text: "Back to top"

heading_anchors: true
copy_code_button: false

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple

# Footer
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/username/biql"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# SEO settings
lang: en_US
author:
  name: "BIQL Contributors"
  email: "contributors@biql.org"

# Social media
social:
  name: "BIDS Query Language"
  links:
    - https://github.com/username/biql

# Custom variables
biql:
  version: "1.0.0"
  release_date: "2024"
  license: "MIT"
  repository: "https://github.com/username/biql"