name: Execute Notebook and Generate Tutorial

on:
  push:
    branches: [ "main", "master" ]
    paths: [ "docs/guide.ipynb" ]
  pull_request:
    branches: [ "main", "master" ]
    paths: [ "docs/guide.ipynb" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert pandas
          # Install BIQL from current source
          pip install -e .

      - name: Clone BIDS examples
        run: |
          mkdir -p docs/example-notebooks
          cd docs/example-notebooks
          git clone https://github.com/bids-standard/bids-examples.git

      - name: Execute notebook
        run: |
          cd docs
          jupyter nbconvert --to notebook --execute --inplace guide.ipynb --ExecutePreprocessor.timeout=300

      - name: Convert notebook to markdown
        run: |
          cd docs
          jupyter nbconvert --to markdown guide.ipynb --output guide.md

      - name: Add Jekyll front matter and navigation
        run: |
          cd docs
          # Create the final tutorial page with Jekyll front matter
          cat > guide_final.md << 'EOF'
          ---
          title: BIQL Tutorial
          nav_order: 3
          ---

          # BIQL Tutorial

          This tutorial demonstrates how to use the BIDS Query Language (BIQL) to query neuroimaging datasets.
          The examples below are automatically executed and updated whenever the documentation is built.

          EOF

          # Append the converted notebook content (skip the title since we add our own)
          tail -n +2 guide.md >> guide_final.md

          # Move to final location
          mv guide_final.md guide.md

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          cd docs
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes
          if git diff --quiet guide.md; then
            echo "No changes to guide.md"
          else
            echo "Changes detected in guide.md"
            git add guide.md guide.ipynb
            git commit -m "🤖 Auto-update guide from notebook execution"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
